### ISSUE TITLE
View Essay Submissions UI

### ISSUE THREAD

**Issue by scottmcglynn** [umgc/fall2024#23]
View listed of submission. Selecting one sends it to the LLM with the attached rubric for grading. The response is handled and the Edit LLM generated Rubric Grade of Essay Submssion screen takes over.

**Comment by scottmcglynn** [comment]
You need to convert this into an actual UI screen that lives in our view folder and incorporate the Dev landing page to link to it.

**Comment by AIohio** [comment]
You need to convert this into an actual UI screen that *lives in our view
folder* (you mean in GitHub?, if yes: I did not get the required support
from Conor as assigned to assist to navigate it, to meet class
specifications as earlier thought, so if someone else could assist on this,
that would be great) and incorporate the *Dev landing page* to link to it
(am not clear with this, I thought this is assigned to someone else? Just a
question). As I have done my side of the job(?!). I had to put in more time
to complete my tasks: View Essay Submission; and earlier Login page,
because I knew this week is going to be very busy for me, as I earlier
hinted to you, on Monday(?). Thank you. Regards.


Iriafen Ohiosikha (Anthony).
